### ISSUE TITLE
Adding new features to the Love Running website

### ISSUE THREAD

**Issue by Flow-matic** [Flow-matic/Lovwe-Running-Agile-Issue-2#1]
In order to **receive benefit** as a **role**, I can **goal/desire** “Submit a Poll Response” as a user I would like to add feedback or leave comments.

**Comment by Flow-matic** [comment]
# Acceptance Criteria
  
   * Acceptance Criteria 1: I am able to verify with the intended recipient of the email that it was received.   
   * Acceptance Criteria 2: The user selects **forgot password**
   * Acceptance Criteria 3: The system lets the user reset a new password.

**Comment by Flow-matic** [comment]
# Tasks
- [ ]  Define Sign-up/Login form style and develop new CSS class
- [ ] Create a new field in the model to track the username
- [ ] Finally test all updates

**Comment by Flow-matic** [comment]
This is completed
