### ISSUE TITLE
Moscows added to Github

### ISSUE THREAD

**Issue by Flow-matic** [Flow-matic/Lovwe-Running-Agile-Issue-2#3]
# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] In order to collect users feedback, as an administrator, I can publish a poll
- [ ] In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the pol
